version: "3.2"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3360:3306
    volumes:
      - .data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokemondata
    networks:
      - pokenet
  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    networks:
      - pokenet
    depends_on:
      - mysql
networks:
  pokenet:
    driver: bridge
